Repository hickeyjohnson/uomi_application, pull requests merged in 2019-03, with the labels that each got.

#13 Facebook login and glossy app icon
  .idea/assetWizardSettings.xml
  .idea/caches/gradle_models.ser
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_glossy_app_icon-web.png
  app/src/main/java/ca/outercove/uomiapplication/LoginRegistrationActivity.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/PreferencesFragment.java
  app/src/main/res/layout-land/activity_login_registration.xml
  app/src/main/res/layout-v26/activity_login_registration.xml
  app/src/main/res/layout/activity_login_registration.xml
  app/src/main/res/mipmap-anydpi-v26/ic_glossy_app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_glossy_app_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_glossy_app_icon.png
  app/src/main/res/mipmap-hdpi/ic_glossy_app_icon_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_glossy_app_icon.png
  app/src/main/res/mipmap-mdpi/ic_glossy_app_icon_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_glossy_app_icon.png
  app/src/main/res/mipmap-xhdpi/ic_glossy_app_icon_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_glossy_app_icon.png
  app/src/main/res/mipmap-xxhdpi/ic_glossy_app_icon_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_glossy_app_icon.png
  app/src/main/res/mipmap-xxxhdpi/ic_glossy_app_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#14 Notifications List in Fragment
  .idea/caches/gradle_models.ser
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/AccountsViewContent.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/NotificationsContent.java
  app/src/main/java/ca/outercove/uomiapplication/dummy/DummyContent.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/NotificationsFragment.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/NotificationsListAdapter.java
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/layout/fragment_notifications_item.xml
  app/src/main/res/layout/fragment_notifications_list.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#16 First Iteration of Network Connectivity
  .idea/caches/gradle_models.ser
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/ca/outercove/uomiapplication/LoginRegistrationActivity.java
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/AccountsViewContent.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/SingleAccountViewContent.java
  app/src/main/java/ca/outercove/uomiapplication/backendCommunication/RequestQueueSingleton.java
  app/src/main/java/ca/outercove/uomiapplication/backendCommunication/WebAPICommunicator.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DashboardFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/NotificationsFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/AccountsViewListAdapter.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/TransactionsListAdapter.java
  app/src/main/res/drawable/uomi3.png
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_single_account.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement, internet connection

#18 Acccount creation is own fragment
  .idea/navEditor.xml
  app/.idea/libraries/Gradle__android_arch_lifecycle_extensions_1_1_1_aar.xml
  app/.idea/libraries/Gradle__com_android_support_customtabs_27_0_2_aar.xml
  app/.idea/libraries/Gradle__com_android_support_preference_v7_28_0_0_aar.xml
  app/.idea/libraries/Gradle__com_facebook_android_facebook_common_4_40_0_aar.xml
  app/.idea/libraries/Gradle__com_facebook_android_facebook_core_4_40_0_aar.xml
  app/.idea/libraries/Gradle__com_facebook_android_facebook_login_4_40_0_aar.xml
  app/.idea/libraries/Gradle__org_fabiomsr_moneytextview_1_1_0_aar.xml
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateAccountDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateAccountFragment.java
  app/src/main/res/layout-v26/dialog_new_account.xml
  app/src/main/res/layout-v26/fragment_account_creation.xml
  app/src/main/res/layout/dialog_new_account.xml
  app/src/main/res/layout/fragment_account_creation.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#19 Adding Swiping on Account and Transaction lists
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteAccountDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteTransactionDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/AccountsViewListAdapter.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/TransactionsListAdapter.java
  app/src/main/res/layout/dialog_delete_account.xml
  app/src/main/res/layout/dialog_delete_transaction.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#20 fixing layout of CreateAccountFragment to work on any phone
  app/src/main/res/layout/fragment_account_creation.xml
Labels: bug, ui

#21 switching base url of webapi to hosted solution
  app/src/main/res/values/strings.xml
Labels: internet connection

#22 Cancel delete automatically returns the item to list.
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteAccountDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteTransactionDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
Labels: enhancement, ui

#24 Delete Transactions from accounts
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
  app/src/main/res/layout/fragment_single_account.xml
Labels: enhancement, internet connection

#26 General Account Improvements
  .idea/navEditor.xml
  app/src/main/java/ca/outercove/uomiapplication/FormattingHelper.java
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateAccountFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateTransactionFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DashboardFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteAccountDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/AccountsViewListAdapter.java
  app/src/main/res/layout/fragment_accounts_view_item.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, internet connection, ui

#27 Back button Navigation
  app/src/main/AndroidManifest.xml
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DashboardFragment.java
Labels: enhancement, ui

#28 Transaction Payer Name and Transaction Add bug fix
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateTransactionFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
Labels: bug, enhancement, ui

#29 User can logout of account
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/PreferencesFragment.java
  app/src/main/res/xml/settings_ui.xml
Labels: enhancement, ui

#30 Polishing up
  app/src/main/java/ca/outercove/uomiapplication/LoginRegistrationActivity.java
  app/src/main/java/ca/outercove/uomiapplication/MainActivity.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/AccountsViewContent.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/NotificationsContent.java
  app/src/main/java/ca/outercove/uomiapplication/appObjects/SingleAccountViewContent.java
  app/src/main/java/ca/outercove/uomiapplication/backendCommunication/RequestQueueSingleton.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/AccountsViewFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateAccountFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/CreateTransactionFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DashboardFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/DeleteTransactionDialogFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/PreferencesFragment.java
  app/src/main/java/ca/outercove/uomiapplication/fragments/SingleAccountFragment.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/AccountsViewListAdapter.java
  app/src/main/java/ca/outercove/uomiapplication/listAdapters/TransactionsListAdapter.java
  app/src/main/res/navigation/nav_main.xml
Labels: enhancement, ui
